import pandas as pd

data = [
    {"title": "Jane Eyre", "author": "Charlotte Brontë", "genre": "Fiction"},
    {"title": "The Stranger", "author": "Albert Camus", "genre": "Philosophical Fiction"},
    {"title": "To Kill a Mockingbird", "author": "Harper Lee", "genre": "Southern Gothic"},
    {"title": "Wuthering Heights", "author": "Emily Brontë", "genre": "Gothic Fiction"},
    {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "genre": "Coming-of-Age Fiction"},
    {"title": "Pride and Prejudice", "author": "Jane Austen", "genre": "Romance"},
    {"title": "The Adventures of Huckleberry Finn", "author": "Mark Twain", "genre": "Adventure Fiction"},
    {"title": "1984", "author": "George Orwell", "genre": "Dystopian"},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck", "genre": "Historical Fiction"},
    {"title": "War and Peace", "author": "Leo Tolstoy", "genre": "Historical Fiction"},
    {"title": "Midnight’s Children", "author": "Salman Rushdie", "genre": "Magic Realism"},
    {"title": "A Portrait of the Artist as a Young Man", "author": "James Joyce", "genre": "Bildungsroman"},
    {"title": "The Magic Mountain", "author": "Thomas Mann", "genre": "Philosophical Fiction"},
    {"title": "Leaves of Grass", "author": "Walt Whitman", "genre": "Poetry"},
    {"title": "Tristram Shandy; and A Sentimental Journey", "author": "Laurence Sterne", "genre": "Satire"},
    {"title": "David Copperfield", "author": "Charles Dickens", "genre": "Bildungsroman"},
    {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "genre": "Modernist Fiction"},
    {"title": "Collected Fictions", "author": "Jorge Luis Borges", "genre": "Short Stories"},
    {"title": "The Aeneid", "author": "Virgil", "genre": "Epic Poetry"},
    {"title": "The Short Stories of Anton Chekhov", "author": "Anton Chekhov", "genre": "Short Stories"},
    {"title": "Mrs. Dalloway", "author": "Virginia Woolf", "genre": "Modernist Fiction"},
    {"title": "Beloved", "author": "Toni Morrison", "genre": "Historical Fiction"},
    {"title": "Gulliver’s Travels", "author": "Jonathan Swift", "genre": "Satire"},
    {"title": "Middlemarch", "author": "George Eliot", "genre": "Realism"},
    {"title": "The Red and the Black", "author": "Stendhal", "genre": "Romantic Realism"},
    {"title": "The Trial", "author": "Franz Kafka", "genre": "Existential Fiction"},
    {"title": "Invisible Man", "author": "Ralph Ellison", "genre": "African American Literature"},
    {"title": "The Divine Comedy", "author": "Dante Alighieri", "genre": "Epic Poetry"},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "genre": "Philosophical Fiction"},
    {"title": "Lolita", "author": "Vladimir Nabokov", "genre": "Psychological Fiction"},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "genre": "Philosophical Fiction"},
    {"title": "Anna Karenina", "author": "Leo Tolstoy", "genre": "Realist Fiction"},
    {"title": "Alice’s Adventures in Wonderland", "author": "Lewis Carroll", "genre": "Fantasy"},
    {"title": "The Iliad", "author": "Homer", "genre": "Epic Poetry"},
    {"title": "To the Lighthouse", "author": "Virginia Woolf", "genre": "Modernist Fiction"},
    {"title": "Catch-22", "author": "Joseph Heller", "genre": "Satire"},
    {"title": "Heart of Darkness", "author": "Joseph Conrad", "genre": "Colonial Literature"},
    {"title": "The Sound and the Fury", "author": "William Faulkner", "genre": "Modernist Fiction"},
    {"title": "Great Expectations", "author": "Charles Dickens", "genre": "Victorian Fiction"},
    {"title": "One Thousand and One Arabian Nights", "author": "Various Authors", "genre": "Folk Tales"},
    {"title": "Absalom, Absalom!", "author": "William Faulkner", "genre": "Southern Gothic"},
    {"title": "Madame Bovary", "author": "Gustave Flaubert", "genre": "Realist Fiction"},
    {"title": "The Odyssey", "author": "Homer", "genre": "Epic Poetry"},
    {"title": "Hamlet", "author": "William Shakespeare", "genre": "Tragedy"},
    {"title": "Moby-Dick or, The Whale", "author": "Herman Melville", "genre": "Adventure Fiction"},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "Tragedy"},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "genre": "Magic Realism"},
    {"title": "Don Quixote", "author": "Miguel de Cervantes Saavedra", "genre": "Satire"},
    {"title": "Ulysses", "author": "James Joyce", "genre": "Modernist Fiction"},
    {"title": "In Search of Lost Time", "author": "Marcel Proust", "genre": "Modernist Fiction"}
]

df = pd.DataFrame(data)

def get_dataset():
    return df